/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package auquemia.view;

import auquemia.DAO.AnimalDAO;
import auquemia.DAO.TutorDAO;
import auquemia.entidades.Animal;
import auquemia.entidades.Tutor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class AnimalJPanel extends javax.swing.JPanel {

    private Animal animal = new Animal();
    private AnimalDAO animaldao = new AnimalDAO();
    private TutorDAO tutordao = new TutorDAO();

    public AnimalJPanel() {
        initComponents();
        DefaultTableModel modeloPadrao = (DefaultTableModel) animalJTable.getModel();
        animalJTable.setRowSorter(new TableRowSorter(modeloPadrao));
        lerTabela();
        carregarBox();
    }

    private void carregarBox() {
        List<Tutor> tutores = tutordao.ler();
        tutorJComboBox.removeAllItems();
        for (Tutor tutor : tutores) {
            tutorJComboBox.addItem(tutor);
        }
    }

    public void lerTabela() {
        DefaultTableModel modeloPadrao = (DefaultTableModel) animalJTable.getModel();
        modeloPadrao.setNumRows(0);

        for (Animal animal : animaldao.ler()) {
            modeloPadrao.addRow(new Object[]{
                animal.getId(), animal.getIdTutor(), animal.getNome(), animal.getEspecie(), animal.getRaca(), animal.getIdade()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaScrollPane = new javax.swing.JScrollPane();
        animalJTable = new javax.swing.JTable();
        nomeJLabel = new javax.swing.JLabel();
        especieJLabel = new javax.swing.JLabel();
        racaJLabel = new javax.swing.JLabel();
        idadeJLabel = new javax.swing.JLabel();
        nomeJTextField = new javax.swing.JTextField();
        especieJTextField = new javax.swing.JTextField();
        racaJTextField = new javax.swing.JTextField();
        idadeJTextField = new javax.swing.JTextField();
        excluirJButton = new javax.swing.JButton();
        atualizarJButton = new javax.swing.JButton();
        limparJButton = new javax.swing.JButton();
        salvarJButton = new javax.swing.JButton();
        idTutorJLabel = new javax.swing.JLabel();
        tutorJComboBox = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1000, 720));

        animalJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID Tutor", "Nome", "Especie", "Raça", "Idade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaScrollPane.setViewportView(animalJTable);

        nomeJLabel.setText("Nome:");

        especieJLabel.setText("Espécie:");

        racaJLabel.setText("Raça:");

        idadeJLabel.setText("Idade:");

        nomeJTextField.addActionListener(this::nomeJTextFieldActionPerformed);

        especieJTextField.addActionListener(this::especieJTextFieldActionPerformed);

        idadeJTextField.addActionListener(this::idadeJTextFieldActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        atualizarJButton.setText("Atualizar");
        atualizarJButton.addActionListener(this::atualizarJButtonActionPerformed);

        limparJButton.setText("Limpar");
        limparJButton.addActionListener(this::limparJButtonActionPerformed);

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(this::salvarJButtonActionPerformed);

        idTutorJLabel.setText("Nome do Tutor:");

        tutorJComboBox.addActionListener(this::tutorJComboBoxActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaScrollPane)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(especieJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(especieJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(racaJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(racaJTextField)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(salvarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(atualizarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(limparJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(excluirJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idadeJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idadeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idTutorJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tutorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {especieJTextField, idadeJTextField, racaJTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeJLabel))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especieJLabel)
                    .addComponent(especieJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(racaJLabel)
                    .addComponent(racaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idadeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTutorJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarJButton)
                    .addComponent(limparJButton)
                    .addComponent(atualizarJButton)
                    .addComponent(excluirJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabelaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {especieJTextField, idadeJTextField, nomeJTextField, racaJTextField});

    }// </editor-fold>//GEN-END:initComponents

    private void atualizarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJButtonActionPerformed
        try {
            Tutor tutor = new Tutor();
            if (animalJTable.getSelectedRow() != -1) {
                animal.setNome(nomeJTextField.getText());
                animal.setEspecie(especieJTextField.getText());
                animal.setRaca(racaJTextField.getText());
                animal.setIdade(idadeJTextField.getText());
                tutor = (Tutor) tutorJComboBox.getSelectedItem();
                animal.setIdTutor(tutor.getId());
                animal.setId((int) animalJTable.getValueAt(animalJTable.getSelectedRow(), 0));
                animaldao.atualizar(animal);
                JOptionPane.showMessageDialog(null, "Registro do animal modificado com sucesso.");
                limparJButtonActionPerformed(evt);
                lerTabela();
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um registro.");
            }
        } catch (RuntimeException re) {
            JOptionPane.showMessageDialog(null, re.getMessage());
            re.printStackTrace();
        }
    }//GEN-LAST:event_atualizarJButtonActionPerformed

    private void limparJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparJButtonActionPerformed
        nomeJTextField.setText("");
        especieJTextField.setText("");
        racaJTextField.setText("");
        idadeJTextField.setText("");
    }//GEN-LAST:event_limparJButtonActionPerformed

    private void especieJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especieJTextFieldActionPerformed

    private void nomeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeJTextFieldActionPerformed

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed
         try {
            Tutor tutor = new Tutor();

            animal.setNome(nomeJTextField.getText());
            animal.setEspecie(especieJTextField.getText());
            animal.setRaca(racaJTextField.getText());
            animal.setIdade(idadeJTextField.getText());
            tutor = (Tutor) tutorJComboBox.getSelectedItem();
            animal.setIdTutor(tutor.getId());
            animaldao.criar(animal);
            JOptionPane.showMessageDialog(null, "Um registro do animal foi salvo com sucesso.");
            limparJButtonActionPerformed(evt);
            lerTabela();
        } catch (RuntimeException re) {
            JOptionPane.showMessageDialog(null, re.getMessage());
            re.printStackTrace();
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int id = (int) animalJTable.getValueAt(animalJTable.getSelectedRow(), 0);
        if (animalJTable.getSelectedRow() != -1) {
            animaldao.deletar(id);
            JOptionPane.showMessageDialog(null, "Registro do animal removido.");
            lerTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um animal para remover.");
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed

    private void idadeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idadeJTextFieldActionPerformed

    private void tutorJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tutorJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable animalJTable;
    private javax.swing.JButton atualizarJButton;
    private javax.swing.JLabel especieJLabel;
    private javax.swing.JTextField especieJTextField;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JLabel idTutorJLabel;
    private javax.swing.JLabel idadeJLabel;
    private javax.swing.JTextField idadeJTextField;
    private javax.swing.JButton limparJButton;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JLabel racaJLabel;
    private javax.swing.JTextField racaJTextField;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JScrollPane tabelaScrollPane;
    private javax.swing.JComboBox<Object> tutorJComboBox;
    // End of variables declaration//GEN-END:variables
}
