/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package auquemia.view;

import auquemia.DAO.AnimalDAO;
import auquemia.entidades.Consulta;
import auquemia.entidades.Animal;
import auquemia.entidades.Veterinario;
import auquemia.DAO.ConsultaDAO;
import auquemia.DAO.VeterinarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class ConsultaJPanel extends javax.swing.JPanel {

    private Consulta consulta = new Consulta();
    private ConsultaDAO consultadao = new ConsultaDAO();
    private AnimalDAO animaldao = new AnimalDAO();
    private VeterinarioDAO veterinariodao = new VeterinarioDAO();

    /**
     * Creates new form ConsultaJPanel
     */
    public ConsultaJPanel() {
        initComponents();
        DefaultTableModel modeloPadrao = (DefaultTableModel) consultaJTable.getModel();
        consultaJTable.setRowSorter(new TableRowSorter(modeloPadrao));
        lerTabela();
        carregarBox();
    }

    private void carregarBox() {
        List<Animal> animais = animaldao.ler();
        animalJComboBox.removeAllItems();
        for (Animal animal : animais) {
            animalJComboBox.addItem(animal);
        }

        List<Veterinario> vets = veterinariodao.ler();
        veterinarioJComboBox.removeAllItems();
        for (Veterinario veterinario : vets) {
            veterinarioJComboBox.addItem(veterinario);
        }
    }

    public void lerTabela() {
        DefaultTableModel modeloPadrao = (DefaultTableModel) consultaJTable.getModel();
        modeloPadrao.setNumRows(0);

        for (Consulta consulta : consultadao.ler()) {
            modeloPadrao.addRow(new Object[]{
                consulta.getId(), consulta.getIdVeterinario(), consulta.getIdAnimal(), consulta.getData(),
                consulta.getMotivo(), consulta.getTemperatura(), consulta.getDiagnostico(), consulta.getStatus(),
                consulta.getValor()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        idVeterinarioJLabel = new javax.swing.JLabel();
        idAnimalJLabel = new javax.swing.JLabel();
        motivoJLabel = new javax.swing.JLabel();
        temperaturaJLabel = new javax.swing.JLabel();
        diagnosticoJLabel = new javax.swing.JLabel();
        statusJLabel = new javax.swing.JLabel();
        valorJLabel = new javax.swing.JLabel();
        consultaJScrollPane = new javax.swing.JScrollPane();
        consultaJTable = new javax.swing.JTable();
        atualizarJButton = new javax.swing.JButton();
        salvarJButton = new javax.swing.JButton();
        limparJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        motivoJTextField = new javax.swing.JTextField();
        temperaturaJTextField = new javax.swing.JTextField();
        diagnosticoJTextField = new javax.swing.JTextField();
        statusJTextField = new javax.swing.JTextField();
        valorJTextField = new javax.swing.JTextField();
        veterinarioJComboBox = new javax.swing.JComboBox<>();
        animalJComboBox = new javax.swing.JComboBox<>();

        jTextField8.setText("jTextField8");

        setPreferredSize(new java.awt.Dimension(1000, 720));

        idVeterinarioJLabel.setText("Veterinario:");

        idAnimalJLabel.setText("Animal:");

        motivoJLabel.setText("Motivo:");

        temperaturaJLabel.setText("Temperatura em °C:");

        diagnosticoJLabel.setText("Diagnóstico:");

        statusJLabel.setText("Status:");

        valorJLabel.setText("Valor:");

        consultaJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Consulta", "ID Veterinario", "ID Animal", "Data", "Motivo", "Temperatura", "Diagnóstico", "Status", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        consultaJScrollPane.setViewportView(consultaJTable);

        atualizarJButton.setText("Atualizar");
        atualizarJButton.addActionListener(this::atualizarJButtonActionPerformed);

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(this::salvarJButtonActionPerformed);

        limparJButton.setText("Limpar");
        limparJButton.addActionListener(this::limparJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        motivoJTextField.addActionListener(this::motivoJTextFieldActionPerformed);

        temperaturaJTextField.addActionListener(this::temperaturaJTextFieldActionPerformed);

        valorJTextField.addActionListener(this::valorJTextFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idVeterinarioJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veterinarioJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idAnimalJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(animalJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(temperaturaJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(temperaturaJTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(motivoJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(motivoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(valorJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(valorJTextField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(statusJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(statusJTextField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(diagnosticoJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(diagnosticoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(limparJButton)
                                .addGap(320, 320, 320)))
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(atualizarJButton)
                        .addGap(79, 79, 79)
                        .addComponent(salvarJButton)
                        .addGap(91, 91, 91))))
            .addComponent(consultaJScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idVeterinarioJLabel)
                    .addComponent(diagnosticoJLabel)
                    .addComponent(diagnosticoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veterinarioJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idAnimalJLabel)
                    .addComponent(statusJLabel)
                    .addComponent(statusJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animalJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motivoJLabel)
                    .addComponent(valorJLabel)
                    .addComponent(motivoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temperaturaJLabel)
                            .addComponent(temperaturaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atualizarJButton)
                            .addComponent(salvarJButton)
                            .addComponent(limparJButton)
                            .addComponent(excluirJButton))
                        .addGap(16, 16, 16)))
                .addComponent(consultaJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void temperaturaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperaturaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperaturaJTextFieldActionPerformed

    private void motivoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motivoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motivoJTextFieldActionPerformed

    private void valorJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorJTextFieldActionPerformed

    private void atualizarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJButtonActionPerformed
        try {
            Animal animal = new Animal();
            Veterinario veterinario = new Veterinario();
            if (consultaJTable.getSelectedRow() != -1) {
                consulta.setMotivo(motivoJTextField.getText());
                consulta.setDiagnostico(diagnosticoJTextField.getText());
                consulta.setStatus(statusJTextField.getText());
                consulta.setTemperatura(Double.parseDouble(temperaturaJTextField.getText()));
                consulta.setValor(Double.parseDouble(valorJTextField.getText()));
                animal = (Animal) animalJComboBox.getSelectedItem();
                consulta.setIdAnimal(animal.getId());
                veterinario = (Veterinario) veterinarioJComboBox.getSelectedItem();
                consulta.setIdVeterinario(veterinario.getId());
                consulta.setId((int) consultaJTable.getValueAt(consultaJTable.getSelectedRow(), 0));
                consultadao.atualizar(consulta);
                JOptionPane.showMessageDialog(null, "Registro da consulta modificado com sucesso.");
                limparJButtonActionPerformed(evt);
                lerTabela();
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um registro.");
            }
        } catch (RuntimeException re) {
            JOptionPane.showMessageDialog(null, re.getMessage());
            re.printStackTrace();
        }
    }//GEN-LAST:event_atualizarJButtonActionPerformed

    private void limparJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparJButtonActionPerformed
        motivoJTextField.setText("");
        temperaturaJTextField.setText("");
        diagnosticoJTextField.setText("");
        statusJTextField.setText("");
        valorJTextField.setText("");
    }//GEN-LAST:event_limparJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int id = (int) consultaJTable.getValueAt(consultaJTable.getSelectedRow(), 0);
        if (consultaJTable.getSelectedRow() != -1) {
            consultadao.deletar(id);
            JOptionPane.showMessageDialog(null, "Registro da consulta removido.");
            lerTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma consulta para remover.");
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed

        try {
            Veterinario veterinario = new Veterinario();
            Animal animal = new Animal();
            consulta.setMotivo(motivoJTextField.getText());
            consulta.setTemperatura(Double.parseDouble(temperaturaJTextField.getText()));
            consulta.setDiagnostico(diagnosticoJTextField.getText());
            consulta.setStatus(statusJTextField.getText());
            consulta.setValor(Double.parseDouble(valorJTextField.getText()));
            animal = (Animal) animalJComboBox.getSelectedItem();
            consulta.setIdAnimal(animal.getId());
            veterinario = (Veterinario) veterinarioJComboBox.getSelectedItem();
            consulta.setIdVeterinario(veterinario.getId());
            consultadao.criar(consulta);
            JOptionPane.showMessageDialog(null, "Um registro da consulta foi salvo com sucesso.");
            limparJButtonActionPerformed(evt);
            lerTabela();
        } catch (RuntimeException re) {
            JOptionPane.showMessageDialog(null, re.getMessage());
            re.printStackTrace();
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> animalJComboBox;
    private javax.swing.JButton atualizarJButton;
    private javax.swing.JScrollPane consultaJScrollPane;
    private javax.swing.JTable consultaJTable;
    private javax.swing.JLabel diagnosticoJLabel;
    private javax.swing.JTextField diagnosticoJTextField;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JLabel idAnimalJLabel;
    private javax.swing.JLabel idVeterinarioJLabel;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton limparJButton;
    private javax.swing.JLabel motivoJLabel;
    private javax.swing.JTextField motivoJTextField;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JLabel statusJLabel;
    private javax.swing.JTextField statusJTextField;
    private javax.swing.JLabel temperaturaJLabel;
    private javax.swing.JTextField temperaturaJTextField;
    private javax.swing.JLabel valorJLabel;
    private javax.swing.JTextField valorJTextField;
    private javax.swing.JComboBox<Object> veterinarioJComboBox;
    // End of variables declaration//GEN-END:variables
}
