/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package auquemia.view;

import auquemia.DAO.ConsultaDAO;
import auquemia.DAO.MedicamentoDAO;
import auquemia.entidades.Consulta;
import auquemia.entidades.Medicamento;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author pedronogg
 */
public class MedicamentoJPanel extends javax.swing.JPanel {

    private Medicamento medicamento = new Medicamento();
    private MedicamentoDAO medicamentodao = new MedicamentoDAO();
    private ConsultaDAO consultadao = new ConsultaDAO();

    /**
     * Creates new form MedicamentoJPanel
     */
    public MedicamentoJPanel() {
        initComponents();
        DefaultTableModel modeloPadrao = (DefaultTableModel) medicamentoJTable.getModel();
        medicamentoJTable.setRowSorter(new TableRowSorter(modeloPadrao));
        lerTabela();
        carregarBox();
    }

    private void carregarBox() {
        List<Consulta> consultas = consultadao.ler();
        consultaJComboBox.removeAllItems();
        for (Consulta consulta : consultas) {
            consultaJComboBox.addItem(consulta);
        }
    }

    public void lerTabela() {
        DefaultTableModel modeloPadrao = (DefaultTableModel) medicamentoJTable.getModel();
        modeloPadrao.setNumRows(0);

        for (Medicamento medicamento : medicamentodao.ler()) {
            modeloPadrao.addRow(new Object[]{
                medicamento.getId(), medicamento.getIdConsulta(), medicamento.getNome(), medicamento.getFormato(),
                medicamento.getFabricante(), medicamento.getDataVencimento()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idConsultaJLabel = new javax.swing.JLabel();
        nomeJLabel = new javax.swing.JLabel();
        formatoJLabel = new javax.swing.JLabel();
        fabricanteJLabel = new javax.swing.JLabel();
        dataValidadeJLabel = new javax.swing.JLabel();
        salvarJButton = new javax.swing.JButton();
        atualizarJButton = new javax.swing.JButton();
        limparJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        veterinarioJScrollPane = new javax.swing.JScrollPane();
        medicamentoJTable = new javax.swing.JTable();
        formatoJTextField = new javax.swing.JTextField();
        nomeJTextField = new javax.swing.JTextField();
        fabricanteJTextField = new javax.swing.JTextField();
        dataValidadeJTextField = new javax.swing.JTextField();
        consultaJComboBox = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1000, 720));

        idConsultaJLabel.setText("Diagnostico da Consulta:");

        nomeJLabel.setText("Nome:");

        formatoJLabel.setText("Formato:");

        fabricanteJLabel.setText("Fabricante");

        dataValidadeJLabel.setText("Data de Validade:");

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(this::salvarJButtonActionPerformed);

        atualizarJButton.setText("Atualizar");
        atualizarJButton.addActionListener(this::atualizarJButtonActionPerformed);

        limparJButton.setText("Limpar");
        limparJButton.addActionListener(this::limparJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        medicamentoJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Medicamento", "ID Consulta", "Nome", "Formato", "Fabricante", "Data de Validade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        veterinarioJScrollPane.setViewportView(medicamentoJTable);

        dataValidadeJTextField.addActionListener(this::dataValidadeJTextFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formatoJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formatoJTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idConsultaJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fabricanteJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fabricanteJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataValidadeJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataValidadeJTextField)))
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(veterinarioJScrollPane))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(salvarJButton)
                .addGap(60, 60, 60)
                .addComponent(atualizarJButton)
                .addGap(60, 60, 60)
                .addComponent(limparJButton)
                .addGap(60, 60, 60)
                .addComponent(excluirJButton)
                .addGap(0, 108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idConsultaJLabel)
                    .addComponent(fabricanteJLabel)
                    .addComponent(fabricanteJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJLabel)
                    .addComponent(dataValidadeJLabel)
                    .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataValidadeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatoJLabel)
                    .addComponent(formatoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(excluirJButton)
                            .addComponent(limparJButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(veterinarioJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvarJButton)
                            .addComponent(atualizarJButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJButtonActionPerformed
        try {
            Consulta consulta = new Consulta();
            if (medicamentoJTable.getSelectedRow() != -1) {

                medicamento.setNome(nomeJTextField.getText());
                medicamento.setFormato(formatoJTextField.getText());
                medicamento.setFabricante(fabricanteJTextField.getText());
                medicamento.setDataVencimento(dataValidadeJTextField.getText());
                consulta = (Consulta) consultaJComboBox.getSelectedItem();
                medicamento.setIdConsulta(consulta.getId());
                medicamento.setId((int) medicamentoJTable.getValueAt(medicamentoJTable.getSelectedRow(), 0));
                medicamentodao.atualizar(medicamento);
                JOptionPane.showMessageDialog(null, "Registro do medicamento modificado com sucesso.");
                limparJButtonActionPerformed(evt);
                lerTabela();
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um medicamento.");
            }
        } catch (RuntimeException re) {
            JOptionPane.showMessageDialog(null, re.getMessage());
            re.printStackTrace();
        }
    }//GEN-LAST:event_atualizarJButtonActionPerformed

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed
        try {
            Consulta consulta = new Consulta();
            medicamento.setNome(nomeJTextField.getText());
            medicamento.setFormato(formatoJTextField.getText());
            medicamento.setFabricante(fabricanteJTextField.getText());
            medicamento.setDataVencimento(dataValidadeJTextField.getText());
            consulta = (Consulta) consultaJComboBox.getSelectedItem();
            medicamento.setIdConsulta(consulta.getId());
            medicamentodao.criar(medicamento);
            JOptionPane.showMessageDialog(null, "Um registro de medicamento foi salvo com sucesso.");
            limparJButtonActionPerformed(evt);
            lerTabela();
        } catch (RuntimeException re) {
            JOptionPane.showMessageDialog(null, re.getMessage());
            re.printStackTrace();
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed

    private void limparJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparJButtonActionPerformed
        nomeJTextField.setText("");
        formatoJTextField.setText("");
        fabricanteJTextField.setText("");
        dataValidadeJTextField.setText("");
    }//GEN-LAST:event_limparJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int id = (int) medicamentoJTable.getValueAt(medicamentoJTable.getSelectedRow(), 0);
        if (medicamentoJTable.getSelectedRow() != -1) {
            medicamentodao.deletar(id);
            JOptionPane.showMessageDialog(null, "Registro do medicamento removido.");
            lerTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um medicamento para remover.");
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed

    private void dataValidadeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataValidadeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataValidadeJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarJButton;
    private javax.swing.JComboBox<Object> consultaJComboBox;
    private javax.swing.JLabel dataValidadeJLabel;
    private javax.swing.JTextField dataValidadeJTextField;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JLabel fabricanteJLabel;
    private javax.swing.JTextField fabricanteJTextField;
    private javax.swing.JLabel formatoJLabel;
    private javax.swing.JTextField formatoJTextField;
    private javax.swing.JLabel idConsultaJLabel;
    private javax.swing.JButton limparJButton;
    private javax.swing.JTable medicamentoJTable;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JScrollPane veterinarioJScrollPane;
    // End of variables declaration//GEN-END:variables
}
