/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package auquemia.view;

/**
 *
 * @author pedronogg
 */
public class MenuJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuJFrame.class.getName());

    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalJPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        entidadesJMenuBar = new javax.swing.JMenuBar();
        animalJMenu = new javax.swing.JMenu();
        animalJMenuItem = new javax.swing.JMenuItem();
        tutorJMenu = new javax.swing.JMenu();
        tutorJMenuItem = new javax.swing.JMenuItem();
        veterinarioJMenu = new javax.swing.JMenu();
        veterinarioJMenuItem = new javax.swing.JMenuItem();
        consultaJMenu = new javax.swing.JMenu();
        consultaJMenuItem = new javax.swing.JMenuItem();
        medicamentoJMenu = new javax.swing.JMenu();
        medicamentoJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AuqueMia");

        principalJPanel.setLayout(new javax.swing.BoxLayout(principalJPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/auquemia/images/1000084602.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        animalJMenu.setText("Animal");

        animalJMenuItem.setText("Acessar");
        animalJMenuItem.addActionListener(this::animalJMenuItemActionPerformed);
        animalJMenu.add(animalJMenuItem);

        entidadesJMenuBar.add(animalJMenu);

        tutorJMenu.setText("Tutor");

        tutorJMenuItem.setText("Acessar");
        tutorJMenuItem.addActionListener(this::tutorJMenuItemActionPerformed);
        tutorJMenu.add(tutorJMenuItem);

        entidadesJMenuBar.add(tutorJMenu);

        veterinarioJMenu.setText("Veterinario");

        veterinarioJMenuItem.setText("Acessar");
        veterinarioJMenuItem.addActionListener(this::veterinarioJMenuItemActionPerformed);
        veterinarioJMenu.add(veterinarioJMenuItem);

        entidadesJMenuBar.add(veterinarioJMenu);

        consultaJMenu.setText("Consulta");

        consultaJMenuItem.setText("Acessar");
        consultaJMenuItem.addActionListener(this::consultaJMenuItemActionPerformed);
        consultaJMenu.add(consultaJMenuItem);

        entidadesJMenuBar.add(consultaJMenu);

        medicamentoJMenu.setText("Medicamento");

        medicamentoJMenuItem.setText("Acessar");
        medicamentoJMenuItem.addActionListener(this::medicamentoJMenuItemActionPerformed);
        medicamentoJMenu.add(medicamentoJMenuItem);

        entidadesJMenuBar.add(medicamentoJMenu);

        setJMenuBar(entidadesJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(principalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(principalJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void animalJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalJMenuItemActionPerformed
        
        AnimalJPanel animal = new AnimalJPanel();
        principalJPanel.removeAll();
        principalJPanel.add(animal);
        principalJPanel.setVisible(false);
        principalJPanel.setVisible(true);
    }//GEN-LAST:event_animalJMenuItemActionPerformed

    private void tutorJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorJMenuItemActionPerformed
        TutorJPanel tutor = new TutorJPanel();
        principalJPanel.removeAll();
        principalJPanel.add(tutor);
        principalJPanel.setVisible(false);
        principalJPanel.setVisible(true);
    }//GEN-LAST:event_tutorJMenuItemActionPerformed

    private void consultaJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaJMenuItemActionPerformed
        ConsultaJPanel consulta = new ConsultaJPanel();
        principalJPanel.removeAll();
        principalJPanel.add(consulta);
        principalJPanel.setVisible(false);
        principalJPanel.setVisible(true);
    }//GEN-LAST:event_consultaJMenuItemActionPerformed

    private void veterinarioJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veterinarioJMenuItemActionPerformed
        VeterinarioJPanel veterinario = new VeterinarioJPanel();
        principalJPanel.removeAll();
        principalJPanel.add(veterinario);
        principalJPanel.setVisible(false);
        principalJPanel.setVisible(true);
    }//GEN-LAST:event_veterinarioJMenuItemActionPerformed

    private void medicamentoJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamentoJMenuItemActionPerformed
        MedicamentoJPanel medicamento = new MedicamentoJPanel();
        principalJPanel.removeAll();
        principalJPanel.add(medicamento);
        principalJPanel.setVisible(false);
        principalJPanel.setVisible(true);
    }//GEN-LAST:event_medicamentoJMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu animalJMenu;
    private javax.swing.JMenuItem animalJMenuItem;
    private javax.swing.JMenu consultaJMenu;
    private javax.swing.JMenuItem consultaJMenuItem;
    private javax.swing.JMenuBar entidadesJMenuBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu medicamentoJMenu;
    private javax.swing.JMenuItem medicamentoJMenuItem;
    private javax.swing.JPanel principalJPanel;
    private javax.swing.JMenu tutorJMenu;
    private javax.swing.JMenuItem tutorJMenuItem;
    private javax.swing.JMenu veterinarioJMenu;
    private javax.swing.JMenuItem veterinarioJMenuItem;
    // End of variables declaration//GEN-END:variables
}
