/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package auquemia.view;

import auquemia.DAO.TutorDAO;
import auquemia.entidades.Tutor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class TutorJPanel extends javax.swing.JPanel {

    private Tutor tutor = new Tutor();
    private TutorDAO tutordao = new TutorDAO();

    /**
     * Creates new form TutorJPanel
     */
    public TutorJPanel() {
        initComponents();
        DefaultTableModel modeloPadrao = (DefaultTableModel) tutorJTable.getModel();
        tutorJTable.setRowSorter(new TableRowSorter(modeloPadrao));
        lerTabela();
    }

    public void lerTabela() {
        DefaultTableModel modeloPadrao = (DefaultTableModel) tutorJTable.getModel();
        modeloPadrao.setNumRows(0);

        for (Tutor tutor : tutordao.ler()) {
            modeloPadrao.addRow(new Object[]{
                tutor.getId(), tutor.getNome(), tutor.getCpf(), tutor.getTelefone(), tutor.getEndereco()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tutorJTable = new javax.swing.JTable();
        nomeJLabel = new javax.swing.JLabel();
        cpfJLabel = new javax.swing.JLabel();
        telefoneJLabel = new javax.swing.JLabel();
        enderecoJLabel = new javax.swing.JLabel();
        nomeJTextField = new javax.swing.JTextField();
        cpfJTextField = new javax.swing.JTextField();
        telefoneJTextField = new javax.swing.JTextField();
        enderecoJTextField = new javax.swing.JTextField();
        salvarJButton = new javax.swing.JButton();
        atualizarJButton = new javax.swing.JButton();
        limparJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 720));

        tutorJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Telefone", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tutorJTable);

        nomeJLabel.setText("Nome:");

        cpfJLabel.setText("CPF:");

        telefoneJLabel.setText("Telefone");

        enderecoJLabel.setText("Endereço");

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(this::salvarJButtonActionPerformed);

        atualizarJButton.setText("Atualizar");
        atualizarJButton.addActionListener(this::atualizarJButtonActionPerformed);

        limparJButton.setText("Limpar");
        limparJButton.addActionListener(this::limparJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(salvarJButton)
                        .addGap(95, 95, 95)
                        .addComponent(atualizarJButton)
                        .addGap(95, 95, 95)
                        .addComponent(limparJButton)
                        .addGap(95, 95, 95)
                        .addComponent(excluirJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enderecoJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enderecoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpfJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telefoneJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {atualizarJButton, excluirJButton, limparJButton, salvarJButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJLabel)
                    .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfJLabel)
                    .addComponent(cpfJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneJLabel)
                    .addComponent(telefoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoJLabel)
                    .addComponent(enderecoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarJButton)
                    .addComponent(atualizarJButton)
                    .addComponent(limparJButton)
                    .addComponent(excluirJButton))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJButtonActionPerformed
        try {
            if (tutorJTable.getSelectedRow() != -1) {
                tutor.setNome(nomeJTextField.getText());
                tutor.setCpf(cpfJTextField.getText());
                tutor.setTelefone(telefoneJTextField.getText());
                tutor.setEndereco(enderecoJTextField.getText());
                tutor.setId((int) tutorJTable.getValueAt(tutorJTable.getSelectedRow(), 0));
                tutordao.atualizar(tutor);
                JOptionPane.showMessageDialog(null, "Registro do tutor modificado com sucesso.");
                limparJButtonActionPerformed(evt);
                lerTabela();
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um registro.");
            }
        } catch (RuntimeException re) {
            JOptionPane.showMessageDialog(null, re.getMessage());
            re.printStackTrace();
        }
    }//GEN-LAST:event_atualizarJButtonActionPerformed

    private void limparJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparJButtonActionPerformed
        nomeJTextField.setText("");
        cpfJTextField.setText("");
        telefoneJTextField.setText("");
        enderecoJTextField.setText("");
    }//GEN-LAST:event_limparJButtonActionPerformed

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed
        try {
            tutor.setNome(nomeJTextField.getText());
            tutor.setCpf(cpfJTextField.getText());
            tutor.setTelefone(telefoneJTextField.getText());
            tutor.setEndereco(enderecoJTextField.getText());
            tutordao.criar(tutor);
            JOptionPane.showMessageDialog(null, "Um registro do tutor foi salvo com sucesso.");
            limparJButtonActionPerformed(evt);
            lerTabela();
        } catch (RuntimeException re) {
            JOptionPane.showMessageDialog(null, re.getMessage());
            re.printStackTrace();
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int id = (int) tutorJTable.getValueAt(tutorJTable.getSelectedRow(), 0);
        if (tutorJTable.getSelectedRow() != -1) {
            tutordao.deletar(id);
            JOptionPane.showMessageDialog(null, "Registro do tutor removido.");
            lerTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um tutor para remover.");
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarJButton;
    private javax.swing.JLabel cpfJLabel;
    private javax.swing.JTextField cpfJTextField;
    private javax.swing.JLabel enderecoJLabel;
    private javax.swing.JTextField enderecoJTextField;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparJButton;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JLabel telefoneJLabel;
    private javax.swing.JTextField telefoneJTextField;
    private javax.swing.JTable tutorJTable;
    // End of variables declaration//GEN-END:variables
}
