/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package auquemia.view;

import auquemia.DAO.VeterinarioDAO;
import auquemia.entidades.Veterinario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author pedronogg
 */
public class VeterinarioJPanel extends javax.swing.JPanel {

    private Veterinario veterinario = new Veterinario();
    private VeterinarioDAO veterinariodao = new VeterinarioDAO();

    /**
     * Creates new form VeterinarioIIJPanel
     */
    public VeterinarioJPanel() {
        initComponents();
        DefaultTableModel modeloPadrao = (DefaultTableModel) veterinarioJTable.getModel();
        veterinarioJTable.setRowSorter(new TableRowSorter(modeloPadrao));
        lerTabela();
    }

    public void lerTabela() {
        DefaultTableModel modeloPadrao = (DefaultTableModel) veterinarioJTable.getModel();
        modeloPadrao.setNumRows(0);

        for (Veterinario veterinario : veterinariodao.ler()) {
            modeloPadrao.addRow(new Object[]{
                veterinario.getId(), veterinario.getNome(), veterinario.getCpf(), veterinario.getTelefone(),
                veterinario.getEspecialidade(), veterinario.getCrmv(), veterinario.getHorasTrabalhadas()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeJLabel = new javax.swing.JLabel();
        cpfJLabel = new javax.swing.JLabel();
        telefoneJLabel = new javax.swing.JLabel();
        especialidadeJLabel = new javax.swing.JLabel();
        crmvJLabel = new javax.swing.JLabel();
        horasTrabalhadasJLabel = new javax.swing.JLabel();
        salvarJButton = new javax.swing.JButton();
        atualizarJButton = new javax.swing.JButton();
        limparJButton = new javax.swing.JButton();
        excluirJButton = new javax.swing.JButton();
        veterinarioJScrollPane = new javax.swing.JScrollPane();
        veterinarioJTable = new javax.swing.JTable();
        nomeJTextField = new javax.swing.JTextField();
        cpfJTextField = new javax.swing.JTextField();
        telefoneJTextField = new javax.swing.JTextField();
        especialidadeJTextField = new javax.swing.JTextField();
        crmvJTextField = new javax.swing.JTextField();
        horasTrabalhadasJTextField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1000, 720));

        nomeJLabel.setText("Nome:");

        cpfJLabel.setText("CPF:");

        telefoneJLabel.setText("Telefone:");

        especialidadeJLabel.setText("Especialidade:");

        crmvJLabel.setText("CRMV:");

        horasTrabalhadasJLabel.setText("Horas de Trabalho:");

        salvarJButton.setText("Salvar");
        salvarJButton.addActionListener(this::salvarJButtonActionPerformed);

        atualizarJButton.setText("Atualizar");
        atualizarJButton.addActionListener(this::atualizarJButtonActionPerformed);

        limparJButton.setText("Limpar");
        limparJButton.addActionListener(this::limparJButtonActionPerformed);

        excluirJButton.setText("Excluir");
        excluirJButton.addActionListener(this::excluirJButtonActionPerformed);

        veterinarioJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Telefone", "Especialidade", "CRMV", "HT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        veterinarioJScrollPane.setViewportView(veterinarioJTable);

        cpfJTextField.addActionListener(this::cpfJTextFieldActionPerformed);

        telefoneJTextField.addActionListener(this::telefoneJTextFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpfJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telefoneJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crmvJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crmvJTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(horasTrabalhadasJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horasTrabalhadasJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(especialidadeJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(especialidadeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(salvarJButton)
                .addGap(18, 18, 18)
                .addComponent(atualizarJButton)
                .addGap(18, 18, 18)
                .addComponent(limparJButton)
                .addGap(18, 18, 18)
                .addComponent(excluirJButton)
                .addGap(0, 444, Short.MAX_VALUE))
            .addComponent(veterinarioJScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeJLabel)
                    .addComponent(especialidadeJLabel)
                    .addComponent(nomeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especialidadeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfJLabel)
                    .addComponent(crmvJLabel)
                    .addComponent(cpfJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crmvJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneJLabel)
                    .addComponent(horasTrabalhadasJLabel)
                    .addComponent(telefoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horasTrabalhadasJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirJButton)
                    .addComponent(limparJButton)
                    .addComponent(atualizarJButton)
                    .addComponent(salvarJButton))
                .addGap(5, 5, 5)
                .addComponent(veterinarioJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void telefoneJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneJTextFieldActionPerformed

    private void cpfJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfJTextFieldActionPerformed

    private void salvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarJButtonActionPerformed
        try {
            veterinario.setNome(nomeJTextField.getText());
            veterinario.setCpf(cpfJTextField.getText());
            veterinario.setTelefone(telefoneJTextField.getText());
            veterinario.setEspecialidade(especialidadeJTextField.getText());
            veterinario.setCrmv(crmvJTextField.getText());

            String horas = horasTrabalhadasJTextField.getText();
            if (!horas.isBlank()) {
                veterinario.setHorasTrabalhadas(Integer.parseInt(horasTrabalhadasJTextField.getText()));
                veterinariodao.criar(veterinario);
                JOptionPane.showMessageDialog(null, "Um registro do veterinario foi salvo com sucesso.");
                limparJButtonActionPerformed(evt);
                lerTabela();
            } else {
                JOptionPane.showMessageDialog(null, "Preencha quantas horas de trabalho o veterinário possui.");
            }
        } catch (RuntimeException re) {
            JOptionPane.showMessageDialog(null, re.getMessage());
            re.printStackTrace();
        }
    }//GEN-LAST:event_salvarJButtonActionPerformed

    private void atualizarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJButtonActionPerformed
        try {
            if (veterinarioJTable.getSelectedRow() != -1) {
                veterinario.setNome(nomeJTextField.getText());
                veterinario.setCpf(cpfJTextField.getText());
                veterinario.setTelefone(telefoneJTextField.getText());
                veterinario.setEspecialidade(especialidadeJTextField.getText());
                veterinario.setCrmv(crmvJTextField.getText());

                String horas = horasTrabalhadasJTextField.getText();
                if (!horas.isBlank()) {
                    veterinario.setHorasTrabalhadas(Integer.parseInt(horasTrabalhadasJTextField.getText()));
                    veterinario.setId((int) veterinarioJTable.getValueAt(veterinarioJTable.getSelectedRow(), 0));
                    veterinariodao.atualizar(veterinario);
                    JOptionPane.showMessageDialog(null, "Registro do veterinario modificado com sucesso.");
                    limparJButtonActionPerformed(evt);
                    lerTabela();
                } else {
                    JOptionPane.showMessageDialog(null, "Preencha quantas horas de trabalho o veterinário possui.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um registro.");
            }
        } catch (RuntimeException re) {
            JOptionPane.showMessageDialog(null, re.getMessage());
            re.printStackTrace();
        }
    }//GEN-LAST:event_atualizarJButtonActionPerformed

    private void limparJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparJButtonActionPerformed
        nomeJTextField.setText("");
        cpfJTextField.setText("");
        telefoneJTextField.setText("");
        especialidadeJTextField.setText("");
        crmvJTextField.setText("");
        horasTrabalhadasJTextField.setText("");
    }//GEN-LAST:event_limparJButtonActionPerformed

    private void excluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirJButtonActionPerformed
        int id = (int) veterinarioJTable.getValueAt(veterinarioJTable.getSelectedRow(), 0);
        if (veterinarioJTable.getSelectedRow() != -1) {
            veterinariodao.deletar(id);
            JOptionPane.showMessageDialog(null, "Registro do veterinario removido.");
            lerTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um veterinario para remover.");
        }
    }//GEN-LAST:event_excluirJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarJButton;
    private javax.swing.JLabel cpfJLabel;
    private javax.swing.JTextField cpfJTextField;
    private javax.swing.JLabel crmvJLabel;
    private javax.swing.JTextField crmvJTextField;
    private javax.swing.JLabel especialidadeJLabel;
    private javax.swing.JTextField especialidadeJTextField;
    private javax.swing.JButton excluirJButton;
    private javax.swing.JLabel horasTrabalhadasJLabel;
    private javax.swing.JTextField horasTrabalhadasJTextField;
    private javax.swing.JButton limparJButton;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JTextField nomeJTextField;
    private javax.swing.JButton salvarJButton;
    private javax.swing.JLabel telefoneJLabel;
    private javax.swing.JTextField telefoneJTextField;
    private javax.swing.JScrollPane veterinarioJScrollPane;
    private javax.swing.JTable veterinarioJTable;
    // End of variables declaration//GEN-END:variables
}
